### ISSUE TITLE
use cpp interface instead of c API

### ISSUE THREAD

**Issue by mpetri** [Enet4/faiss-rs#22]
Having played with accessing faiss via the [cxx](https://github.com/dtolnay/cxx) crate it was reasonably straightforward to create interoperability between rust and faiss. 

Is there a reason why the use of the C api is preferred for interacting with faiss?

**Comment by Enet4** [comment]
There happens to be a combination of reasons for faiss-rs to be integrated this way.
The most obvious one is that `cxx` did not exist back then. These bindings were first created in early 2018, and `cxx` only became a somewhat viable choice in 2019. The only other reasonable choice that could have been made back then was to try to bindgen the C++ API directly, potentially with poor results when working with standard C++ containers and such.

Creating a C API for Faiss was an opportunity to fill in the gap while opening doors for other technologies to use Faiss without SWIG or trying to get along with C++. And since this works, there isn't a high enough benefit/cost ratio to justify a rewrite that would also influence the current expectations of the library. For such an idea to go through, there should be a somewhat smooth transition process, and/or it should retain the possibility of setting up all relevant build parameters from the main Faiss project.

You can read more into the process of creating faiss-rs in the blog posts "Taking the long road: bindings for a vector similarity search library", [Part 1](https://medium.com/@e_net4/taking-the-long-road-part-1-97e6e41f6b05) & [Part 2](https://medium.com/@e_net4/taking-the-load-road-part-2-rust-bindings-for-a-vector-similarity-search-library-914fbc1ec5ed).

**Comment by mpetri** [comment]
Thanks. Closing this issue.
